import os

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
IMGBB_API_KEY = os.getenv("IMGBB_API_KEY", "")
INSTAGRAM_ACCESS_TOKEN = os.getenv("INSTAGRAM_ACCESS_TOKEN", "")
INSTAGRAM_BUSINESS_ACCOUNT_ID = os.getenv("INSTAGRAM_BUSINESS_ACCOUNT_ID", "")

# X (Twitter) OAuth 2.0
X_OAUTH2_CLIENT_ID = os.getenv("X_OAUTH2_CLIENT_ID", "")
X_OAUTH2_CLIENT_SECRET = os.getenv("X_OAUTH2_CLIENT_SECRET", "")
X_OAUTH2_REFRESH_TOKEN = os.getenv("X_OAUTH2_REFRESH_TOKEN", "")
